### ISSUE TITLE
In WP 4.7 new function `get_networks()` break in Wordpress 4.5.4 or under 4.6.0

### ISSUE THREAD

**Issue by emgk** [stuttter/wp-multi-network#104]
The last commit #91 showing error in wordpress < 4.6.0 . 

> Fatal error: Call to undefined function get_networks() in /var/www/html/wp454/wp-content/plugins/wp-multi-network-master/wp-multi-network/includes/classes/class-wp-ms-networks-list-table.php on line 70

I think the new function `get_network()` should call with some validation, otherwise it will breaks under Wordpress with < 4.6.0 version .

```
if ( function_exists( 'get_network' ) ) {
        // get_network();
} else {
       // wp_get_network();
}
```

**Comment by JJJ** [comment]
To fix this, we'd need to shim this plugin with a check in 14 places, which I guess I'd rather not do.

`get_network()` was introduced in 4.6.0, and the minimum version was bumped to that on August 16, 2016. If you're stuck on an older version of WordPress, you'll need to use an older version of this plugin. Sorry about that.
