### ISSUE TITLE
Register "/networks" API endpoints

### ISSUE THREAD

**Issue by JJJ** [stuttter/wp-multi-network#106]
Per today's multisite development chat, we've concluded that `/network` REST API endpoints can be started here first. This will allow us to more easily scrutinize what works best, and what belongs in WordPress core vs. what is plugin territory.

With this plugin's track record of funneling Network improvements upstream, I think this is a good idea.

Paging @richardtape, @jeremyfelt, and friends. 💜

**Comment by richardtape** [comment]
What sort of resources are we considering making available when someone hits `/networks` and same question for something like `/network/2` ?

**Comment by rmccue** [comment]
Quick note: that should be `/networks` and `/networks/2`. Keep the nouns plural, and singular items (resources) should be hierarchically underneath the list (collection).

Happy to offer review and feedback :)
