### ISSUE TITLE
WordPress 4.7 Use get_network() over wp_get_network()

### ISSUE THREAD

**Issue by thefrosty** [stuttter/wp-multi-network#108]
```
PHP Notice: wp_get_network is deprecated since version 4.7.0!
Use get_network() instead. in /../wp-includes/functions.php on line 3828 
```

**Comment by r66r** [comment]
Hi @thefrosty 

I think that you're still using the old 1.8.1 version from the WordPress plugins repository.

In issue #90, some improvements have been made to correct this, which are effective in the current version 2.1.0 of the plugin. Just download the master ZIP from this GitHub repo and your problem will be solved.

@JJJ: Is it planned to update the WordPress plugins repo soon?

**Comment by JJJ** [comment]
Yeah, I'll update wporg soon.
