### ISSUE TITLE
Unable to logout on secondary networks

### ISSUE THREAD

**Issue by RavanH** [stuttter/wp-multi-network#117]
While there is no problem logging out on the primary network (or any of its sub-sites) I'm encountering issues logging out when I'm on secondary network sites (primary or sub-sites it does not seem to matter).

When trying to log out, I get redirected to a page with message "Are you sure you want to log out?" from where I can follow the link "log out" and I land on the wp-login.php form page. It looks like I've been logged out fine but when revisiting the site's front page I see the admin bar still there on top and I can re-enter the admin without passing the login form.

Has anyone encountered this problem? Can it be reproduced?

Notes: 
1. this is on a VPS, running on Nginx, PHP7 and using Redis. 
2. The multisite was first set up using https://github.com/EasyEngine/easyengine ... 
3. The issue occurs both for Super Admin as for regular Admin users.

The "Are you sure" message page has an URL like http://sub.secondary.net/wp-login.php?action=logout&_wpnonce=xxxxx (notice there IS a nonce there!) while the logout link has href like http://sub.secondary.net/wp-login.php?action=logout&_wpnonce=yyyyy (notice there IS another nonce!) which then redirects to http://sub.secondary.net/wp-login.php?action=logout&_wpnonce=xxxxx (notice there IS a nonce there!) which redirects immediately to http://sub.secondary.net/wp-login.php?loggedout=true showing the expected login form.

Still, the user is not really logged out at all :(

**Comment by christianwach** [comment]
Check out https://core.trac.wordpress.org/ticket/39497 which seems to be the cause of this. Temporary solution is in the first comment.

Cheers, Christian

**Comment by RavanH** [comment]
Hi @christianwach that's amazing... Chose the method suggested in https://core.trac.wordpress.org/ticket/39497#comment:4 (setting a COOKIEHASH in wp-config.php) and the issue was fixed. Thanks!

**Comment by christianwach** [comment]
@RavanH Bear in mind that the behaviour you're seeing will be reverted in WordPress 4.7.4, so you'll probably want to stop setting `COOKIEHASH` or `WP_SITEURL` when you upgrade.

**Comment by RavanH** [comment]
@christianwach what would be the risk of setting one cookiehash across all networks? And would something like `define( 'COOKIEHASH', md5( $_SERVER['HTTP_HOST'] ) );` be safer then?

Besides, a reversal to pre-4.7 would mean then that there will be NO cookiehash used at all on secondary networks? If so, then it might be a good idea to have cookiehash defined on the fly by WP Multi-Network instead of leaving it up to WP core using wp_guess_url() as it is now or reverting to no cookiehash as it did before...

**Comment by JJJ** [comment]
Glad y'all were able to get this sorted out.

Going to close, but feel free to chat here as needed!
