### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by ouun** [stuttter/wp-multi-network#120]
Thank you very much for this very useful plugin. Just testing it. Within a sub-network in the "networks" dashboard page I get the following error:

> Warning: array_filter() expects parameter 1 to be array, string given in /plugins/wp-multi-network/wp-multi-network/includes/classes/class-wp-ms-networks-list-table.php on line 379

Best regards,

Philipp

**Comment by lisandi** [comment]
Where exactly do you get that error, I can't reproduce it. Could you please write down step by step to reproduce that error. Thanks
Andi
