### ISSUE TITLE
Feedback: Success with WP 4.9.1 and multi-network 1.8.1

### ISSUE THREAD

**Issue by agrajagco** [stuttter/wp-multi-network#122]
From a "testing in production" standpoint, I've been successful bringing in existing non multi-network sites constructed in WP, into a shared multi-network deploy.  I am using the WP all-in-one migration with their muli-site extension to do this. (There is stilla minor issue and updating of the wp_#_options to fix home and siteurl, but once done, things are working.)

Next we'll be migrating sites constructed under 4.6.1. / Wp multi-network 1.8.1, I'll upate here.

The question is; is multi-network going to become an actual feature of wordpress release versions? Perhaps in the 5.x line of releases?

If not is there going to be an update to supported release version listed on the wordpress.org for this?

**Comment by JJJ** [comment]
We are systematically and methodically bringing code from this plugin into core when it fits other core initiatives. It's unlikely this plugin will get merged into core wholesale, but it is considered the "canonical" multi-network plugin amongst the multisite component maintainers.

If you want multiple networks, it seems this is the one to use. +1
