### ISSUE TITLE
Revert back to standard multi site network

### ISSUE THREAD

**Issue by blur33** [stuttter/wp-multi-network#129]
Is there anything that I should know before deleting the unneeded networks, removing the config information and deactivating the plugin?

Will the images and everything for the currently active sites still work correctly?

**Comment by agrajagco** [comment]
Make backups before attempting of your database and filesystem.  I have deleted websites in a multi-network collection and the other networks (domains, sites) were not impacted.  But the backups should protect you in case anything goes wrong.

**Comment by JJJ** [comment]
Deleting a network permanently deletes all of the sites in that network, calling the WordPress function `wpmu_delete_blog()` on every site in the network. Therefore, it also attempts to delete all of the media on all of those sites, all of the user connections, etc...

Existing sites on the current network you are wanting to keep will all be OK.
