### ISSUE TITLE
Network name defaults to "New Network"

### ISSUE THREAD

**Issue by sudeervc** [stuttter/wp-multi-network#152]
When creating a network, we added a network name, but that netowrk name is not being recognized instead it will show the network name as "New Network". We had to edit the network to update the name.

Thanks,
Sudeer.

**Comment by Manakio** [comment]
I can confirm this behavior as well. I just created a new network on a system that has 17 total networks and over 100 sites and the new network defaulted to "New Network" and I had to go back in and rename it...

**Comment by nathansmonk** [comment]
I also see this behaviour

**Comment by Manakio** [comment]
This is still an ongoing issue (PHP 7.4 & WP 5.3.2)
