### ISSUE TITLE
Way to prevent sub-network super administrators from deleting plugins?

### ISSUE THREAD

**Issue by MLutt** [stuttter/wp-multi-network#154]
Pretty much what the subject says, we had issues with a network administrator deleting a plugin on "his" network and downing a range of sites on other networks doing so... Is there a way to permit a user to manage sites on the network without providing access to the plugin deletion/limiting a sub-network admin to actions affecting only their network and not everyone else?

Also, is there a way to limit the space used on a per-network base?

I could not find a documentation or already asked question regarding both - sorry if the fruitless search is due to me not having searched the right places (since especially the first issue seems pretty basic)...

**Comment by Manakio** [comment]
We use Admin Menu Editor for this. We hide the plugins menu from other Super Admins (which we rarely grant anyway)

**Comment by logicfish** [comment]
so a super-admin could craft a request and delete all the plugins.

**Comment by JJJ** [comment]
Vanilla WordPress Multisite comes with the option to hide/disable the Plugins menu entirely. 

<img width="332" alt="jjj-on-2021-08-29-at-20-26-29@2x" src="https://user-images.githubusercontent.com/88951/131273096-ecc331ba-1d5c-4d6d-a718-d7f5ede62e84.png">

It's saved as a network option (site meta) using the `menu_items` key. You can also use the `mu_menu_items` filter to disable other top-level menu items.

None of that really helps if you need your administrators to be able to activate or deactivate plugins still.

You could also explore using the `DISALLOW_FILE_MODS` and/or `DISALLOW_FILE_EDIT` constants.
