### ISSUE TITLE
Maintenance, and Blogs Network setup

### ISSUE THREAD

**Issue by AlexdeBorba** [stuttter/wp-multi-network#157]
Hello everyone,

I will start by asking if this plugin is maintained since, through WordPress Plugins, it states that it was last updated two years ago, and the support forums seem abandoned.

Also, how to create a subnetwork such as /blogs, so that when creating a new one under the Blogs network, it is generated as /blogs/new?

I have been running tests on a stagging environment and either something is skipping my attention, or the option to create a new blog under a network seems unviable.

Thank you in advance.

**Comment by JJJ** [comment]
Hello @AlexdeBorba 👋

If I understand your question correctly, the option still exists under Sites > Add New.

I've opened up the GitHub Discussions feature in this repository. Let's continue this there, if you're still interested?
