### ISSUE TITLE
Current github release is 2.4.0 - wordpress version is 2.2.0 - is there a reason?

### ISSUE THREAD

**Issue by agrajagco** [stuttter/wp-multi-network#158]
Multi-Network team.

Again, thanks for all your effort over the years.  I have to ask, are users expected to no longer trust the wordpress.com plugins information for this awesome plugin, and just follow along on github?  Or is there a reason we should be waiting for an official update to the wordpress site?  Is there a blog or website we should be following as users of this plugin?

Thanks in advance for any updated information.

**Comment by agrajagco** [comment]
Also - from the readme.md - it points to this site for information on how to create a proper sunrise.php file for nested site paths within a network.

**Comment by agrajagco** [comment]
I'll gladly volunteer to document / test as needed as well!

**Comment by PeterDaveHello** [comment]
Any chance v2.4.0 will also be uploaded on https://wordpress.org/plugins/wp-multi-network/? Thanks!

**Comment by MevoDOTsite** [comment]
I have the same remark as OP: "thanks for all your effort over the years"!
And the same questions about the  potential reasons why an older version is still on WP and the link to create sunrise.php.

Thanks.

**Comment by agrajagco** [comment]
Multi-network team, can anyone please speak to your remaining user community who have tried to contribute in the wordpress forum with help and content who are reaching out to here... 

It is now a security issue to run this plugin in a wordpress installation that is at a supported release level.

Is this project going to communicate with us, or should this be communicated to no longer a project that is maintained.  Something should be said so we know what to do (hang in there or go away and rebuild some other way).

Please?  Can someone provide some insight to the users?

**Comment by JJJ** [comment]
Sorry for the radio silence. I wasn't getting notifications for this project. No idea why yet, but I'll look into it.

I'll ship some version of 2.4.x to WordPress.org ASAP. The version number will depend on what's all included.

If anyone here needs more access than they have to be more helpful here, I will make sure you have anything you need.
