### ISSUE TITLE
Why not maintained on WP.org

### ISSUE THREAD

**Issue by ttodua** [stuttter/wp-multi-network#162]
I couldn't find a pinned issue or explanation here on GH, why on WP.org this plugin is abandoned, while it's maintained here?

**Comment by agrajagco** [comment]
I think this code is becoming internal to WP perhaps?  Maybe the silence is its being rolled in as a base WP feature (I can wish, can't I?)

**Comment by Manakio** [comment]
Now wouldn't that be the cats meow!

**Comment by wordfishgroup** [comment]
Any further news on support of wp-multi-network?

**Comment by JJJ** [comment]
This plugin will not be abandoned as long as I am alive. I'm even working on a plan for that, too. ❤️
