### ISSUE TITLE
Warning: filter_input(): Unknown filter with ID 67108864 in class-wp-ms-networks-admin.php on line 823

### ISSUE THREAD

**Issue by ttodua** [stuttter/wp-multi-network#164]
When I try to add new network, I get:

`Warning: filter_input(): Unknown filter with ID 67108864 in ....path/includes/classes/class-wp-ms-networks-admin.php on line 823`

also, on  line 989 and 990.

btw, i use PHP 8.

**Comment by JJJ** [comment]
Working on a PR for this now.
