### ISSUE TITLE
Multiple domains on a single Site on Multisite

### ISSUE THREAD

**Issue by coderesolution** [stuttter/wp-multi-network#167]
Hello,

We have a website built on the WP Multisite Network which has just a single Site right now. We need to add a few additional domains that point to the exact same Site, so users see the same theme, content, everything.

At the moment we have the domains point to the same server, but they automatically redirect to `/wp-signup.php?new=additional-domain.com` which is breaking everything and need this to not happen.

We would greatly appreciate your support / suggestions here.

Thank you.

**Comment by alexlii1971** [comment]
I am not the plugin author.

Are you sure it support domain mapping?

**Comment by coderesolution** [comment]
What do you mean, sorry? Are you asking if WP Multisite supports domain mapping @alexlii1971?

**Comment by alexlii1971** [comment]
> What do you mean, sorry? Are you asking if WP Multisite supports domain mapping @alexlii1971?

As for as I know, it does not support domain mapping.

But if I am wrong, just let me know.

**Comment by alexlii1971** [comment]
By the way, if I did not misunderstand, you have more than one domain, and you want to map the domains on different multi-site or subsite, am I right?

If yes, What I can tell you is that we need using a domain mapp plugin to map a domain onto a subsite of multisite year's ago.

But, you do not need a plugin for domain mapping for now, please check at https://wordpress.org/support/article/wordpress-multisite-domain-mapping/

But if you activate this plugin of “wp-multi-network”, the above method will not work.

**Comment by JJJ** [comment]
Hello coderesolution 👋

@alexlii1971 is correct that this plugin does not provide the functionality that you seek, which is traditionally called "domain mapping" or "site aliasing".

This plugin only helps create higher-level Networks to group multiple Sites into.

Sorry for the confusion!
