### ISSUE TITLE
Author link discussion

### ISSUE THREAD

**Issue by JJJ** [stuttter/wp-multi-network#175]
Recent changes to the author link are great in that they recognize just about every major contributor to this project, but also have some drawbacks:

* David and Bryan haven't contributed since 2013 and 2010.
* It's visually lengthy, causing crowding in the table cell.
* Links require additional maintenance. Even though I doubt anyone is switching sites soon, it will be easily overlooked when it happens.

## What it is now

Our individual names with links to our sites:

<img width="1032" alt="jjj-on-2021-08-20-at-10-35-56@2x" src="https://user-images.githubusercontent.com/88951/130257925-a1b55453-d9c1-4960-b2e8-3fdde8f7c11e.png">

# My proposal

Switching the link to point to Triple J Software, Inc. like I've done in other projects:

<img width="1038" alt="jjj-on-2021-08-20-at-10-42-51@2x" src="https://user-images.githubusercontent.com/88951/130258827-dd5b2f21-ef0a-416f-9592-c778144ef1f6.png">

# Acknowledgements

I started Triple J Software, Inc. in 2018 with the intention of moving my personal plugins to it, perhaps to monetize them, but largely to protect their longevity, trademarks, etc... To date, this company has generated $0 in revenue. I did a bunch of research in 2018 and concluded a nonprofit foundation was logistically more complicated to operate than I was able to do alone, even though I believe that is ultimately my preference and where I think everything belongs someday.

I do not want to or mean to devalue anyone contributions, and certainly do not want to hurt feelings.

I also feel like many of ours' visions for merging this into WordPress core is gone, as interest is relatively low and the codebases are evolving in ways that aren't necessarily in alignment with each other.

Lastly, there are other contributors to this project that are not listed here - @felixarntz, @jeremyfelt, and everyone else who's submitted a pull request. I feel, personally, that it's unintentionally exclusionary to omit some people, and also unrealistic to include all people, in this small window of a user-interface area.

What does everyone think? ❤️

cc @rmccue @spacedmonkey @felixarntz @jeremyfelt

**Comment by jeremyfelt** [comment]
I don't actually thing I've submitted any code to WP Multi Network. 😱 Probably opinions though? :)

But! IMO, the author name/link associated with the plugin in the admin is not a good place for listing many individual contributors. I think it's okay (results vary, obviously) for the maintainer or maintaining company to use their name and link as a place holder instead. I think this is less confusing for users of plugins overall. It can answer "who do I contact for help?" or "who is responsible for this plugin?"

Contributors and other project roles can be better documented elsewhere. That could be the readme, a separate contributors document, the GitHub contributors view, etc... I think the answer changes based on the project.

If an individual project does ever become complex enough to have a variety of roles, then I think it's valuable to describe those [in more detail](https://varyingvagrantvagrants.org/docs/en-US/governance/) than any author link can.

**Comment by spacedmonkey** [comment]
Sorry, I made this change. Before it was a unformatted list of user ids, that looked messy and was just tidying it up. 

I am happy with this being changed to Triple J Software, Inc. and with the link. I would like the readme.txt to saying something like this. 

"This project is maintained on github. The maintainers are @JJJ, @felixarntz and @spacedmonkey. " Then maybe a note about people who have contributed a lot in the past. I would also update the README.md on github. See this [example](https://github.com/TimeIncUK/enhanced-post-cache#credits). 

 Anyone who hasn't submitted code in 5+ years, should be removed from SVN and github push access as well, IMO. But worth pinging those people to see they are okay with that.
