### ISSUE TITLE
Wordpress Multi-site with Multi-network

### ISSUE THREAD

**Issue by aspapi** [stuttter/wp-multi-network#189]
Hello everyone,

I have set up a multi-network WordPress Multi-site on AWS Lightsail using the WP Multi Network
 by Triple J Software, Inc. but need to know how to install multiple Let's Encrypt SSL certificates for each network within the multi-site using Bitnami's bncert-tool or any other tool that will do the job.
Any suggestions on how to go about it

**Comment by wasanajones** [comment]
FYI I ended up simply adding network  site domains to Cloudflare and use their SSL... emails still in question however and will be using Let's Encrypt for those. 

the Let's Encrypt is handled at the server. DirectAdmin allows assigning to all 'pointer' URL including subdomains ( ie mail.example.com )

**Comment by JJJ** [comment]
SSL certs are a bit outside the scope of this plugin, I'm afraid, but you are certainly on the right path! It's likely best to have the certs up front on a load balancer & proxy, and simply let WordPress and this plugin serve the content after.
