### ISSUE TITLE
Throwing error message upon Network creation - no user being added to network

### ISSUE THREAD

**Issue by wasanajones** [stuttter/wp-multi-network#192]
I was able to easily create a new network a few weeks ago. Now trying on several sites I get an error message upon creating the network and the network does not get a user/admin assigned to it.

"There has been a critical error on this website." gets thrown upon creation - however, the network is created and the site is created. The site is assigned the admin... however the network doesn't have a user... so can't administer the network. 

any ideas? thanks.

**Comment by wasanajones** [comment]
plugin conflict...  still trying to find it, but something activated on Primary site

**Comment by JJJ** [comment]
Interesting! Thank you for letting us know here. 🙌
