### ISSUE TITLE
Creating a new site in a network for WP Multi Network

### ISSUE THREAD

**Issue by ZGMCLUB** [stuttter/wp-multi-network#193]
Hi, how are you?

I am new to WP Multi Network and I like it very much but I have run into some issues. 

Do I have to add the Cookies? And if so, where? In the wp-config.php as well?
I would greatly appreciate it if you could also let me know if there is anything else I should look into. This is really a neat plugin. 

Thank you! 

Best Regards,
James

/ Cookies
define( 'COOKIEHASH',         md5( 'yourrootdomain.com' ) );
define( 'COOKIE_DOMAIN',      'yourrootdomain.com'        );
define( 'ADMIN_COOKIE_PATH',  '/' );
define( 'COOKIEPATH',         '/' );
define( 'SITECOOKIEPATH',     '/' );
define( 'TEST_COOKIE',        'thing_test_cookie' );
define( 'AUTH_COOKIE',        'thing_'          . COOKIEHASH );
define( 'USER_COOKIE',        'thing_user_'     . COOKIEHASH );
define( 'PASS_COOKIE',        'thing_pass_'     . COOKIEHASH );
define( 'SECURE_AUTH_COOKIE', 'thing_sec_'      . COOKIEHASH );
define( 'LOGGED_IN_COOKIE',   'thing_logged_in' . COOKIEHASH );

**Comment by JJJ** [comment]
Yes, in your wp-config. And you will want to customize most of those values, too!
