### ISSUE TITLE
Render CSS if is_admin_bar_showing()

### ISSUE THREAD

**Issue by carstingaxion** [stuttter/wp-multi-network#195]
Hello @JJJ ,

the styles related to the admin bar menu will be rendered to the front-end output, no matter the admin bar is showing or not. This is a chance for improvement I think.

I would suggest adding something like:
```php
if ( ! is_admin_bar_showing() ) {
	return;
}
```
to the very beginning of [`public function admin_print_styles()`](https://github.com/stuttter/wp-multi-network/blob/master/wp-multi-network/includes/classes/class-wp-ms-networks-admin-bar.php#L41).

*What do you think?*

**Comment by JJJ** [comment]
Hey @carstingaxion 👋 That makes sense to me! 👍

**Comment by carstingaxion** [comment]
Nice to agree again on a small enhancement. 

I'll create a PR and let you know.
