### ISSUE TITLE
Site can be moved to network with conflicting subdomain

### ISSUE THREAD

**Issue by rmccue** [stuttter/wp-multi-network#48]
If I have a site on network 2 with the subdomain `foobar.network2.example.com`, and try to move across a site from the main network with the same subdomain (`foobar.example.com`), WPMN happily does this without complaining.

This causes two sites in the same network to both have the same subdomain, and hence same full URL. :-1: 

WPMN should check for this when moving, and a) fail to move it at all, and b) offer to move and rename (after running through the uniqueness process).

**Comment by johnjamesjacoby** [comment]
I decided to stick with `domain_exists()` for this.

* It enables twin sites between networks, which may be a thing you might want
* It's what core uses
* It's got what plants crave
* Introduced `wp_validate_site_url()` which is largely lifted from `wpmu_validate_blog_signup()` to not only look for duplicate URLs on the same network, it also looks for sign-ups, users, and does the basic regex to ensure subdomains & paths don't contain illegal names or characters

Marking as closed.
