### ISSUE TITLE
Single Sign-on redirect loop

### ISSUE THREAD

**Issue by zagriyen** [stuttter/wp-multi-network#53]
Hi, when i put the single sign-on snippet with my primary domain I've got a redirect loop when i go to a another network

```
// Cookies
define( 'COOKIEHASH',        md5( 'yourdomain.com' ) );
define( 'COOKIE_DOMAIN',     'yourdomain.com'        );
define( 'ADMIN_COOKIE_PATH', '/' );
define( 'COOKIEPATH',        '/' );
define( 'SITECOOKIEPATH',    '/' );
define( 'TEST_COOKIE',        'thing_test_cookie' );
define( 'AUTH_COOKIE',        'thing_'          . COOKIEHASH );
define( 'USER_COOKIE',        'thing_user_'     . COOKIEHASH );
define( 'PASS_COOKIE',        'thing_pass_'     . COOKIEHASH );
define( 'SECURE_AUTH_COOKIE', 'thing_sec_'      . COOKIEHASH );
define( 'LOGGED_IN_COOKIE',   'thing_logged_in' . COOKIEHASH );
```

**Comment by johnjamesjacoby** [comment]
Hi. Did you replace "yourdomain.com" and "thing_" with yours?

**Comment by zagriyen** [comment]
Hi, i replace them by "jm_" and it doesn't work. 
but i use 2 diferents domain, network 1 domain1 and network 2 domain2
maybe it's the problem

**Comment by johnjamesjacoby** [comment]
For single-sign-on to work, you'll need more than just cookie sharing. You'll need to do some fancy redirecting to drop & read the appropriate cookies. That's a bit beyond the scope of WPMN for now, but it would be ideal if it were built in.

**Comment by johnjamesjacoby** [comment]
SSO is going to end up in another plugin, since it's not 100% guaranteed to be part of multiple network installation types.
