### ISSUE TITLE
Single Sign On, Cookie Not Enabled

### ISSUE THREAD

**Issue by steven-klein** [stuttter/wp-multi-network#54]
This plugin is awesome, but I can seem to get the single sign on experience working.

I've added and updated the Cookie constants to my config file, but I'm still prompted for a username and password at each network, and WordPress is saying cookies are blocked or not supported, but they definitely are.

**Comment by johnjamesjacoby** [comment]
If the domains are different, than you'll need additional code & configuration to get all domains reading & writing cookies to their proper locations. This is currently out of scope for WPMN, but likely should come baked in at some point.

**Comment by johnjamesjacoby** [comment]
SSO will end up in a separate plugin. I started development of it last week.
