### ISSUE TITLE
Failling sites on WP 4.4

### ISSUE THREAD

**Issue by phoob** [stuttter/wp-multi-network#63]
After upgrading to wp4.4, and upgrading this plugin to 1.7.0, I am not able to assign sites to more than one network. When trying to assign sites to another network all other networks loses their sites. also, now i get network.zero domains for sites i try to visit. What's happening?

Ok this is what I did:
* I already had a multi network site running wp4.3 and wpm 1.6.0 (I think)
* Upgraded to wp4.4 and wpm 1.7.0 (to avoid crash because of duplicate functions
* Started fiddling around in /wp-admin/network/admin.php?page=networks&id=1&action=edit_network – trying to edit sites and move them from network to network.
* suddenly i realize none of my sites are working any more... only the root sites of each network worked
* Then I realize that when I moved a few sites to one network, then moving some other sites to another network, the first network lost all its sites
* eventually i just went into the database and edited each sites wp_options -> siteurl and home (url) as well as the wp_blogs table. site_urls were then http://network.zero/xyz/, and I edited them back to their former subdomains.  I got things working now. But am a little scared...

Here are my MS settings in wp-config:
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', $_SERVER['HTTP_HOST']);
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
define( 'WP_HOME',    'http://' . $_SERVER['HTTP_HOST'] );
define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] );

**Comment by phoob** [comment]
Related: I now tried moving a site starting from here: /wp-admin/network/sites.php moving the site network1.domain.com/siteone/ to network2.domain.com/siteone/. But the result was that the site's url ended up being:
* http://network2.domain.comsiteone (notice the missing "/")
Even more interesting: when I tried moving it back to network1, the site url ended up being 
* http://network1.domain.comiteone (notice the missing "/" AND the missing "s"…)

**Comment by johnjamesjacoby** [comment]
This is no good at all. Really sorry that this happened to you.

I'll investigate and fix asap.

**Comment by johnjamesjacoby** [comment]
The `move_site()` function looks a bit botched. Still looking into this...

**Comment by phoob** [comment]
Thanks :)






On Sun, Feb 7, 2016 at 6:12 PM -0800, "John James Jacoby" <notifications@github.com> wrote:












The move_site() function looks a bit botched. Still looking into this...

**Comment by johnjamesjacoby** [comment]
Okay. This is at least better, if not completely fixed.

Are you able to test the latest master branch and confirm?

**Comment by phoob** [comment]
Hi! Tried now. As you say, it is not THAT bad anymore. But still, when I try to move a site to a network, all other networks lose their sites (except for the main site) (from /wp-admin/network/admin.php?page=networks&id=2&action=edit_network). I had to go into the database to fix the sites, but this time I only had to correct `site_id` in `wp_blogs` (from `0` to `2` in this case)

**Comment by phoob** [comment]
Would you please consider opening this ticket again? There are still significant issues...
