### ISSUE TITLE
redirected to many times

### ISSUE THREAD

**Issue by skulmunkie** [stuttter/wp-multi-network#73]
i have a main multi network site:
http://example.com

and sub network sites
http://example.com/network1
http://example.com/network2

i then create a subsite on network2

http://example.com/network2/site1

when going to this subsite the page is not being rendered properly.  In addition if i try to navigate the the admin panel of that site http://example.com/network2/site1/wp-admin I get the error that the site redirected to many times.

any help would be greatly appreciated.

**Comment by skulmunkie** [comment]
It appears if i navigate to 
http://example.com/network2/site1/wp-admin/index.php then the admin panel loads fine.

But when i goto appearance, the themes do not seem to exists.  This is only happening on a subsite of a sub network.  

my htaccess looks like:
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]

</IfModule>

**Comment by johnjamesjacoby** [comment]
To have sites live multiple directories deep will require a custom `sunrise.php` to help guide your WordPress installation towards understanding what the special cases are.

**Comment by lacimarsik** [comment]
Thanks @johnjamesjacoby - I had a similar problem as @skulmunkie and got it resolved by constructing `sunrise.php` - this [article](https://paulund.co.uk/wordpress-multisite-nested-paths) helped me do that

**Comment by JJJ** [comment]
Hi @lacimarsik. Thanks for chiming in!

I'll close this issue, also recommending that same article. If anyone wanted to submit a pull request to update the documentation to include it and/or credit that article for any future edits, that would be great!
