### ISSUE TITLE
Feature request: Make global users optional

### ISSUE THREAD

**Issue by nathansmonk** [stuttter/wp-multi-network#83]
Being able to have a network of multisites that users are only able to log into the sites they're assigned to would be advantageous.

**Comment by johnjamesjacoby** [comment]
Great idea! But! Network roles will likely be a separate plugin, and I'll make sure this one integrates nicely with that one. 💯

**Comment by nathansmonk** [comment]
As a temporary workaround, I added a mu-plugin that does the following...

`
if( ! function_exists('is_user_logged_in') ) {
   function is_user_logged_in() {
      if ( is_user_member_of_blog() ) {
           $user = wp_get_current_user();
           return $user->exists();
      }
   }
}
`
