### ISSUE TITLE
1.7.0 version was deleted in wordpress.org

### ISSUE THREAD

**Issue by romulodl** [stuttter/wp-multi-network#88]
We currently use this plugin on a wordpress `4.5.3` using the version `1.7.0`.

This version was deleted in https://wordpress.org/plugins/wp-multi-network/developers/ so now we are forced to update to `1.8.1` which reqiuires wordpress `4.6` but we cannot update yet to `4.6`. Could you please restore the `1.7.0` version in wordpress or add this plugin to the official main [packagist](https://packagist.org/)?

**Comment by johnjamesjacoby** [comment]
Sorry about that. I've retagged 1.7.0 on WordPress.org, and the zip will get automatically packaged within the next 15 minutes (that's just the way WordPress.org works with these old tags.)

Curious, is there a decent way to add a WordPress minimum version to `composer.json`?

**Comment by johnjamesjacoby** [comment]
The zip is now live: https://downloads.wordpress.org/plugin/wp-multi-network.1.7.0.zip

**Comment by johnjamesjacoby** [comment]
@romulodl Let me know here if you have any other issues with 1.7.0. We could release a 1.7.1 with support for the WordPress 4.5 branch if we need to.

**Comment by schrapel** [comment]
What would happen if you added `"johnpbloch/wordpress": "4.6"` to the require in your `composer.json`?

We have been using 1.7.0 on 4.5.3 but we are not ready to use 4.6 yet. So I am not sure if 1.7.1 is needed unless there is something we've not noticed working

**Comment by johnjamesjacoby** [comment]
> What would happen if you added "johnpbloch/wordpress": "4.6" to the require in your composer.json?

I'm not sure, exactly. 🎱 

> I am not sure if 1.7.1 is needed unless there is something we've not noticed working

If something comes up, I'm here to help. 💯

**Comment by romulodl** [comment]
Hello John,

Sorry for the late late reply. The `1.7.0` is working correctly!

Thanks!
