### ISSUE TITLE
Filter the networks for the current super admin user into the Networks Admin panel 

### ISSUE THREAD

**Issue by r66r** [stuttter/wp-multi-network#89]
In the "My Networks" page `wp-admin/index.php?page=my-networks`, the user only sees the networks where he's super admin.

In the "All Networks" page `wp-admin/network/admin.php?page=networks`, the user sees all the networks.

This behavior has to be corrected, because without that, a super admin user can change everything in all networks, even if he's not a super admin of a network.

**Comment by r66r** [comment]
The reason is that in 'My Networks' page, the list of networks is obtanined with 'user_has_networks()' (see [here](https://github.com/stuttter/wp-multi-network/blob/1de4ee71ea58c8cb4df7ebdc63483b4f4b60043f/includes/classes/class-wp-ms-networks-admin.php#L646)).

But in the "All Nerworks" page, the list of networks is obtained with the `WP_MS_Networks_List_Table()` class (see [here](https://github.com/stuttter/wp-multi-network/blob/1de4ee71ea58c8cb4df7ebdc63483b4f4b60043f/includes/classes/class-wp-ms-networks-admin.php#L302)), where the select query in the 'prepare_items()' method isn't filtered for the current user (see [here](https://github.com/stuttter/wp-multi-network/blob/1de4ee71ea58c8cb4df7ebdc63483b4f4b60043f/includes/classes/class-wp-ms-networks-list-table.php#L66)).

**Comment by johnjamesjacoby** [comment]
> This behavior has to be corrected

We can't, yet. There is a difference between a "super admin" and a "network admin", and super admins have total and complete access to all screens all the time.

Network admins can't see "Networks" UI, only super admins can. Until there's a legitimate "Global admin UI" and/or a real "My Networks" interface.

**Comment by r66r** [comment]
OK, I understand. So let's wait and see.
Ref. tickets [#37526](https://core.trac.wordpress.org/ticket/37526), [#37593](https://core.trac.wordpress.org/ticket/37593)
