### ISSUE TITLE
wp_get_network() has been deprecated in WP 4.7

### ISSUE THREAD

**Issue by r66r** [stuttter/wp-multi-network#90]
As mentioned in title (https://core.trac.wordpress.org/ticket/37553).

You can find it here:
- functions.php [line 22](https://github.com/stuttter/wp-multi-network/blob/c70a80d8a712b1abee45d7ff3d5ecd19be072d0d/includes/functions.php#L22)
- functions.php [line 93](https://github.com/stuttter/wp-multi-network/blob/c70a80d8a712b1abee45d7ff3d5ecd19be072d0d/includes/functions.php#L93)
- class-wp-ms-networks-cli.php [line 49](https://github.com/stuttter/wp-multi-network/blob/8bf74296792a173573d1197aaf9c7a8c02012405/includes/classes/class-wp-ms-networks-cli.php#L49)
- compat.php [line 173](https://github.com/stuttter/wp-multi-network/blob/8bf74296792a173573d1197aaf9c7a8c02012405/includes/compat.php#L173)
- class-wp-ms-networks-admin.php [line 342](https://github.com/stuttter/wp-multi-network/blob/1de4ee71ea58c8cb4df7ebdc63483b4f4b60043f/includes/classes/class-wp-ms-networks-admin.php#L342)
- class-wp-ms-networks-admin.php [line 462](https://github.com/stuttter/wp-multi-network/blob/1de4ee71ea58c8cb4df7ebdc63483b4f4b60043f/includes/classes/class-wp-ms-networks-admin.php#L462)

**Comment by johnjamesjacoby** [comment]
Replacement is done.

I'm going to check out he return values, but this should be good to go.
