### ISSUE TITLE
Maximize the use of WPMS core functions (since WP 4.6)

### ISSUE THREAD

**Issue by r66r** [stuttter/wp-multi-network#94]
In version 1.8.1 and since WP 4.6, some SQL queries can be replaced by the native functions of WordPress using the classes WP_Site_Query and WP_Network_query.

**Comment by r66r** [comment]
Some appear to be easy:
- functions.php, `get_main_site_for_network()`, [line 107](https://github.com/stuttter/wp-multi-network/blob/master/includes/functions.php#L107)
- functions.php, `add_network()`, [line 335](https://github.com/stuttter/wp-multi-network/blob/master/includes/functions.php#L335)
- functions.php, `delete_network()`. [line 597](https://github.com/stuttter/wp-multi-network/blob/master/includes/functions.php#L597)
- edit-network.pvp, `wpmn_edit_network_assign_sites_metabox()`, [line 98](https://github.com/stuttter/wp-multi-network/blob/master/includes/metaboxes/edit-network.php#L98)
- move_site.php, `wpmn_move_site_list_metabox()`, [line 25](https://github.com/stuttter/wp-multi-network/blob/master/includes/metaboxes/move-site.php#L25)
- class-wp-ms-networks-admin.php, `delete_network_page()`, [line 471](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L471)
- class-wp-ms-networks-admin.php, `delete_multiple_network_page()`, [line 574](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L574) and [line 579](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L579)
- class-wp-ms-networks-admin.php, `reassign_sites_handler()`, [line 891](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L891)

Some need more reflexions:
- functions.php, `user_has_networks()`, [line 66](https://github.com/stuttter/wp-multi-network/blob/master/includes/functions.php#L66)
- class-wp-ms-networks-admin.php, `my_networks_page()`, [line 651](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L651)

**Comment by r66r** [comment]
In a few days, I will propose you a patch to correct the queries which do not affect too much the plugin. But it would be interesting to have a feedback on this subject before.

**Comment by JJJ** [comment]
Thanks for this. This is great to see!

**Comment by JJJ** [comment]
Most of these appear to be completed. What's left are unlikely to ever have core functions, so I think we can safely close this now.

Thanks!
