### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Unsupported operand types in ...

### ISSUE THREAD

**Issue by rekmla** [stuttter/wp-multi-network#95]
We're not running 4.6 yet due to the Requests changes (http_api_curl hook no longer available).

We had been running the master branch of wp-multi-network, but had to back off to 1.8.1 because of the following error:

[] PHP Fatal error:  Uncaught Error: Unsupported operand types in .../wp-admin/includes/class-wp-list-table.php:284
Stack trace:
#0 .../plugins/wp-multi-network/includes/classes/class-wp-ms-networks-list-table.php(82): WP_List_Table->set_pagination_args(Array)
#1 .../plugins/wp-multi-network/includes/classes/class-wp-ms-networks-admin.php(303): WP_MS_Networks_List_Table->prepare_items()
#2 .../plugins/wp-multi-network/includes/classes/class-wp-ms-networks-admin.php(287): WP_MS_Networks_Admin->all_networks_page()
#3 .../wp-includes/plugin.php(525): WP_MS_Networks_Admin->networks_page_router('')
#4 .../wp-admin/admin.php(236): do_action('toplevel_page_n...')
#5 .../wp-admin/network/admin.php(13): require_once('/srv/www/common...')
#6 {main}

  thrown in .../wp-admin/includes/class-wp-list-table.php on line 284

**Comment by JJJ** [comment]
4.6.0 is now the minimum required WordPress version, thanks to a bunch of Site & Network improvements that directly benefit this plugin. Sorry for the inconvenience!
