### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by Sneezry** [stuttter/wp-multi-network#97]
Could you please fix these security issues for this plugin? Thanks.
[TwC Security Guidance 2.pdf](https://github.com/stuttter/wp-multi-network/files/532462/TwC.Security.Guidance.2.pdf)

**Comment by JJJ** [comment]
Interestingly, these were addressed already for what will be 2.1.0.

See:

* 5ba462c3a3ec762d9bc3ab31e1a1d6b49c5f4b1e
* abda134d8d59a1ac81546a9b67f9ebd3e939322c
* 6774123c2c4d38ddc4706eac378a0f162e362a7e
* b11549a8a74e2d53072856ea521a1925493cc6ff
* b992aecf68b1560b8a1bb1f39a412e4320b4bafc and ef3a94d35dfd3fff9b6b0ef82f0b10c9e8c0b066
